<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i>Resources</h2>
		</div>
		<div class="box-content">
			<style type="text/css">
				table.datatable th:first-child,table.datatable th:last-child{
					text-align: center;
				}
				table.datatable th:first-child{
					width: 5%;
				}
				
				table.datatable th:last-child{
					width: 10%;
				}
				table.datatable td:first-child,table.datatable td:last-child{
					text-align: center;
					white-space: nowrap;
				}
			</style>
			
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
				<thead>
					<th>ID</th>
					<th>Name</th>
					<th>Actions</th>
				</thead>
				<tbody>
					<?php foreach($this->resources as $resource) :?>
					<tr>
						<td><?php echo $resource->id; ?></td>
						<td><?php echo $resource->name; ?> </td>
						<td>
							<a href="<?php echo $this->baseUrl('/admin/resource/edit/' . $resource->id); ?>" class="btn btn-primary">Edit</a>
							<a href="<?php echo $this->baseUrl('/admin/resource/delete/' . $resource->id); ?>" class="btn btn-danger">Delete</a>
						</td>
					</tr>

					<?php endforeach; ?>
				</tbody>
			</table>
			<a href="<?php echo $this->baseUrl('/admin/resource/add'); ?>" class="btn btn-primary">New</a>
		</div>
	</div>
</div>