<div class="wrapper">
<div class="image-holder">
    <img src="<?php echo $this->baseUrl('/images/watermark.png');?>" class="login-image"/>
</div>
<div class="login-banner">
    <h1>Admissions Resources</h1>
</div>
<form action="/user/dologin" method="post">
        <label for="username">Username</label>
        <input type="text" name="username" />
        <br>
        <label for="password">Password</label>
        <input type="password" name="password" />
</form>
</div>