<form action="<?php echo $this->baseUrl('/admin/content/doedit'); ?>" method="post">
	<div class="form-elements">
		<label for="message_subject">Subject</label>
		<div class="form-controls">
			<input type="text" name="message_subject" />
		</div>
	</div>
	<div class="form-elements">
		<label for="message_body">Body</label>
		<div class="form-controls">
			<textarea name="message_body" rows="30" cols="50"></textarea>
		</div>
	</div>
	<div class="form-elements">
	<?php foreach (($this->departments) as $department) : ?>
		<span class="cb-holder">
		<label for="department_<?php echo $department->id; ?>"><?php echo $department->name; ?></label>		
		<input type="checkbox" name="department[]" id="<?php echo $department->id; ?> " />
		</span>
	<?php endforeach; ?>
	</div>
	<div class="form-elements">
		<div class="form-controls">
			<input type="submit" value="Submit">
		</div>
	</div>
</form>

