<div id="content-first">
    <div class="header">
        Admissions Resource
    </div>
    <ul>
        <?php foreach($this->colleges as $college) : ?>
        <li class="clicksy" id="<?php echo $college->id; ?>">
            <span class="main-text">
                <?php echo $college->name; ?>
            </span>
            <span class="ficons">
                <i class="icon-angle-right"></i>
            </span>
        </li>
        <?php endforeach;?>
    </ul>
</div>

<div id="content-second" style="background-color: purple !important;">
    <div class="header" id="header-second-page">
        <i class="icon-angle-left"></i>
    </div>
    <ul id="second-list">
    </ul>
</div>

<script>
$('.clicksy').click(function() {
    $('#content-first').animate({
        right: '100%'
    }, 500, function() {
    });
    $('#content-second').animate({
        left: '0%'
    }, 500, function() {
        $.ajax({
            type: "GET",
            url: "<?php echo $this->url(array('id' => '4'), 'restdepartmentsbycollege', true); ?>",
            success: function(data) {
                $('#second-list').append('<li><span class="main-text"> asdf </span> </li>');
                console.log(data);
            }
        });
    });
});

$('#header-second-page').click(function() {
    $('#content-first').animate({
        right: '0%'
    }, 500);
    $('#content-second').animate({
        left: '100%'
    }, 500, function() {
        console.log("here");
    });
});


</script>
