<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i>Colleges</h2>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
				<thead>
					<th>ID</th>
					<th>Name</th>
					<th style="white-space:nowrap;width:1px;">Actions</th>
				</thead>
				<tbody>
					<?php foreach($this->colleges as $college) :?>
					<tr>
						<td><?php echo $college->id; ?></td>
						<td><?php echo $college->name; ?> </td>
						<td style="text-align:center;white-space:nowrap;width:1px;">
							<a href="<?php echo $this->baseUrl('/admin/colleges/edit/' . $college->id); ?>" class="btn btn-primary">Edit</a>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			<a href="<?php echo $this->baseUrl('/admin/colleges/add'); ?>" class="btn btn-primary"> New </a>
		</div>
	</div>
</div>