<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Strixa Game Designs');
?>

<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css');?>
</head>
<body>
	<div class="content_wrapper">
		<div class="header">
			<div class="breadcrumb_navigation">
				<ul>
					<li>Home</li>
					<li>Something Else</li>
					<li>Nope!</li>
				</ul>
			</div>
		</div>
		<div class="content">
	    	<?php echo $this->layout()->content; ?>
	    </div>
	    <div class="footer">  	
	    </div>
	</div>
</body>
</html>
