<!DOCTYPE html>
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Work Thing');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
    <link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/bootstrap-cerulean.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/bootstrap-responsive.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/charisma-app.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/jquery-ui-1.8.21.custom.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/fullcalendar.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/fullcalendar.print.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/chosen.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/uniform.default.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/colorbox.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/jquery.cleditor.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/jquery.noty.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/noty_theme_default.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/elfinder.min.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/elfinder.theme.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/jquery.iphone.toggle.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/opa-icons.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/uploadify.css')); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl('css/admin/font-awesome.min.css')); ?>

    <?php echo $this->headScript()->appendFile($this->baseUrl('/js/admin/jquery.js')); ?>
	<?php echo $this->headLink(); ?>
</head>
<body>
<div class="row-fluid">
    <div class="span12 navbar">
        <div class="navbar-inner">
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 main-menu-span">
            <div class="well nav-collapse sidebar-nav">
                <ul class="nav nav-tabs nav-stacked main-menu">
                    <li class="nav-header hidden-tablet">Main</li>
                    <li><a  href="<?php echo $this->baseUrl('/admin/users'); ?>"><i class="icon-user"> </i><span class="hidden-tablet">Users</span></a></li>
                    <li><a class="ajax-link" href="#"><i class="icon-frown"> </i><span class="hidden-tablet">Logout</span></a></li>
                    <li class="nav-header hidden-tablet"><span class="hidden-tablet">Resources</span></li>
                    <li><a class="ajax-link" href="<?php echo $this->baseUrl('/admin/resource'); ?>"><i class="icon-folder-close-alt"> </i><span class="hidden-tablet">Resource</span></a></li>
                    <li><a class="ajax-link" href="<?php echo $this->baseUrl('/admin/departments'); ?>"><i class="icon-folder-close"> </i><span class="hidden-tablet">Departments</span></a></li>
                    <li><a class="ajax-link" href="<?php echo $this->baseUrl('/admin/colleges'); ?>"><i class="icon-group"> </i><span class="hidden-tablet">Colleges</span></a></li>
                </ul>
            </div>
        </div>
        <div id="content" class="span10">
            <ul class="breadcrumb">
                <li></li>
                <li></li>
            </ul>
           <?php echo $this->layout()->content; ?>

        </div>
   </div>
</div>
    <!-- jQuery -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery-1.7.2.min.js'); ?>"></script>
    <!-- jQuery UI -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery-ui-1.8.21.custom.min.js'); ?>"></script>
    <!-- transition / effect library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-transition.js'); ?>"></script>
    <!-- alert enhancer library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-alert.js'); ?>"></script>
    <!-- modal / dialog library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-modal.js'); ?>"></script>
    <!-- custom dropdown library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-dropdown.js'); ?>"></script>
    <!-- scrolspy library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-scrollspy.js'); ?>"></script>
    <!-- library for creating tabs -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-tab.js'); ?>"></script>
    <!-- library for advanced tooltip -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-tooltip.js'); ?>"></script>
    <!-- popover effect library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-popover.js'); ?>"></script>
    <!-- button enhancer library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-button.js'); ?>"></script>
    <!-- accordion library (optional, not used in demo) -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-collapse.js'); ?>"></script>
    <!-- carousel slideshow library (optional, not used in demo) -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-carousel.js'); ?>"></script>
    <!-- autocomplete library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-typeahead.js'); ?>"></script>
    <!-- tour library -->
    <script src="<?php echo $this->baseUrl('/js/admin/bootstrap-tour.js'); ?>"></script>
    <!-- library for cookie management -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.cookie.js'); ?>"></script>
    <!-- calander plugin -->
    <script src='/js/admin/fullcalendar.min.js'></script>
    <!-- data table plugin -->
    <script src='/js/admin/jquery.dataTables.min.js'></script>

    <!-- chart libraries start -->
    <script src="<?php echo $this->baseUrl('/js/admin/excanvas.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.flot.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.flot.pie.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.flot.stack.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.flot.resize.min.js'); ?>"></script>
    <!-- chart libraries end -->

    <!-- select or dropdown enhancer -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.chosen.min.js'); ?>"></script>
    <!-- checkbox, radio, and file input styler -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.uniform.min.js'); ?>"></script>
    <!-- plugin for gallery image view -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.colorbox.min.js'); ?>"></script>
    <!-- rich text editor library -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.cleditor.min.js'); ?>"></script>
    <!-- notification plugin -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.noty.js'); ?>"></script>
    <!-- file manager library -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.elfinder.min.js'); ?>"></script>
    <!-- star rating plugin -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.raty.min.js'); ?>"></script>
    <!-- for iOS style toggle switch -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.iphone.toggle.js'); ?>"></script>
    <!-- autogrowing textarea plugin -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.autogrow-textarea.js'); ?>"></script>
    <!-- multiple file upload plugin -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.uploadify-3.1.min.js'); ?>"></script>
    <!-- history.js for cross-browser state change on ajax -->
    <script src="<?php echo $this->baseUrl('/js/admin/jquery.history.js'); ?>"></script>
    <!-- application script for Charisma demo -->
    <script src="<?php echo $this->baseUrl('/js/admin/charisma.js'); ?>"></script>


</body>
</html>
