<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Strixa Game Designs');
?>

<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
	
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css'); ?>
	<?php echo $this->headLink(); ?>
</head>
<body>
   	<?php echo $this->layout()->content; ?>
</body>
</html>
