<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Strixa Game Designs');
?>

<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
	
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css'); ?>
	<?php echo $this->headLink(); ?>
</head>
<body>
	Variables available to view:
      messages:  Array of arrays where each array is comprised of an element with key 'type' whose value will be one of 'negative', 'neutral', or 'positive' and key 'message' whose value is a string that represents something the server wishes to communicate with teh user.


   	<?php echo $this->layout()->content; ?>
</body>
</html>
