<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Marketing & Communications - Resources');
?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta charset="utf-8">

	    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <?php $this->headLink()->appendStylesheet($this->baseUrl('/css/ratchet.css')); ?>

    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
    <link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>

    <?php $this->headScript()->appendFile($this->baseUrl('/js/jquery.js')); ?>
    <script type="application/javascript" src="<?php echo $this->baseUrl('/js/add2home.js'); ?>"> </script>
    <?php $this->headScript()->appendFile($this->baseUrl('/js/ratchet.js')); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
       <?php echo $this->layout()->content; ?>
</body>
</html>
