<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Strixa Game Designs');
?>

<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
	<link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>

    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/admin/main.css'); ?>
	<?php echo $this->headLink(); ?>
</head>
<body>
<div class="header">
	<a href="<?php echo $this->baseUrl('/admin'); ?>">ARMS</a>

	<div class="navigation">
		<ul class="nav">
			<li><a href="Users">Users</a></li>
			<li><a href="/admin/emailtemplate">Content</a></li>
			<li><a href="Logout">Logout</a></li>
		</ul>
	</div>
</div>
<div class="content">
   	<?php echo $this->layout()->content; ?>
</div>


</body>
</html>
