<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle('Work Thing');
?>

<?php echo $this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta();?>
    <?php echo $this->headTitle();?>
    <link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>

    
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/default/main.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/default/font-awesome.min.css'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl('/js/jquery.js')); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
       <?php echo $this->layout()->content; ?>
</body>
</html>
