<ul class="menu college_list">
	<li class="header">Admissions Resource</li>
	
    <?php foreach($this->colleges as $college) : ?>
    <li class="item" data-mid="<?php echo $college->id; ?>">
        <?php echo $college->name; ?>
    </li>
    <?php endforeach;?>
</ul>
<ul class="menu department_list">
	<li class="header">Return to Colleges</li>
</ul>
<ul class="menu resource_list">
	<li class="header">Return to Departments</li>
</ul>

<script>
var is_animating = false;
var is_loading = false;


function loadDepartments(){
	if(is_loading){
		return;
	}
	is_loading = true;

	$.get(
        "<?php echo $this->url(array('model' => 'departmentsbycollege'), 'rest/io/get', true); ?>",
        {
        	id: $(this).data('mid') 
        },
        function(response){
        	if(!is_loading){
        		return;
        	}

        	if(response.data.length == 0){
        		$('<li>')
					.addClass('item')
					.addClass('no_department_indicator')
					.text("No Resources Available")
					.appendTo($('.menu.department_list'));
			}else{
				var new_items = $('<div>');
				
				
	        	$.each(response.data, function(val){
					$('<li>')
						.data('mid',this.id)
						.addClass('item')
						.text(this.name)
						.click(loadResources)
						.appendTo(new_items);
			    });
			    
			    new_items
					.children().appendTo($('.menu.department_list'));
			}

			is_loading = false;
		}
    );
    
    scrollToDepartmentList();
}

function unloadDepartments(){
	scrollToCollegeList(function(){
		is_loading = false;
		
		$('.menu.department_list .item')
			.remove();
	});
}

function loadResources(){
	if(is_loading){
		return;
	}
	is_loading = true;

	$.get(
        "<?php echo $this->url(array('model' => 'resourcesbydepartment'), 'rest/io/get', true); ?>",
        {
        	id: $(this).data('mid') 
        },
        function(response){        	
        	if(!is_loading){
        		return;
        	}

        	if(response.data.length == 0){
        		$('<li>')
					.addClass('item')
					.addClass('no_resource_indicator')
					.text("No Resources Available")
					.appendTo($('.menu.resource_list'));
        	}else{
        		var new_items = $('<div>');
        		
        		
	        	$.each(response.data, function(val){
					$('<li>')
						.addClass('item')
						.text(this.name)
						.appendTo(new_items);
			    });
			    
			    new_items
					.children().appendTo($('.menu.resource_list'))
			}

			is_loading = false;
		}
    );
	
	scrollToResourceList();
}

function unloadResources(){
	if(is_animating){
		return;
	}
	is_animating = true;

	scrollToDepartmentList(function(){
		is_loading = false;
		
		$('.menu.resource_list .item')
			.remove();
	});
}

function scrollToCollegeList(on_scroll_complete){    
    if(is_animating){
		$('.menu').finish();
	}else{
		is_animating = true;
	}

	var college_menu = $('.menu.college_list');
	var visible_menu = $('.menu').filter(function(){if($(this).offset().left == 0){return true}});
	
		
	//Is the visible menu logically to the right, or left of the departments menu?
	var new_left = visible_menu.offset().left > college_menu.offset().left ? '100%' : '-100%';
	
	
	visible_menu
		.animate({ left: new_left }, 500, function(){	
			is_animating = false;

			if(on_scroll_complete instanceof Function){
				on_scroll_complete.call(document);
			}
		});
	
	college_menu
		.animate({ left: '0%' }, 500);
}

function scrollToDepartmentList(on_scroll_complete){
	if(is_animating){
		$('.menu').finish();
	}else{
		is_animating = true;
	}

	var department_menu = $('.menu.department_list');
	var visible_menu = $('.menu').filter(function(){if($(this).offset().left == 0){return true}});
	
		
	//Is the visible menu logically to the right, or left of the departments menu?
	var new_left = visible_menu.offset().left > department_menu.offset().left ? '100%' : '-100%';
	

	visible_menu
		.animate({ left: new_left }, 500, function(){	
			is_animating = false;

			if(on_scroll_complete instanceof Function){
				on_scroll_complete.call(document);
			}
		});
	
	department_menu
		.animate({ left: '0%' }, 500);
}

function scrollToResourceList(on_scroll_complete){
	if(is_animating){
		$('.menu').finish();
	}else{
		is_animating = true;
	}

	var resource_menu = $('.menu.resource_list');
	var visible_menu = $('.menu').filter(function(){if($(this).offset().left == 0){return true}});
	
		
	//Is the visible menu logically to the right, or left of the departments menu?
	var new_left = visible_menu.offset().left > resource_menu.offset().left ? '100%' : '-100%';
	

	visible_menu
		.animate({ left: new_left }, 500, function(){	
			is_animating = false;

			if(on_scroll_complete instanceof Function){
				on_scroll_complete.call(document);
			}
		});
	
	resource_menu
		.animate({ left: '0%' }, 500);
}


$('.menu.college_list .item')
	.click(loadDepartments);
		
$('.menu.department_list .header')
	.click(unloadDepartments);
	
$('.menu.resource_list .header')
	.click(unloadResources);
	
</script>
