<div id="content-first">
    <div class="header">
        Admissions Resource
    </div>
    <ul>
        <?php foreach($this->colleges as $college) : ?>
        <li class="clicksy fc-text" id="<?php echo $college->id; ?>">
                <?php echo $college->name; ?>
                <!--span class="ficons"-->
                <!--0i class="icon-angle-right"></i>
            <!--span-->
        </li>
        <?php endforeach;?>
    </ul>
</div>

<div id="content-second" style="background-color: purple !important;">
    <div class="header" id="header-second-page">
        <i class="icon-angle-left"></i>
    </div>
    <ul id="second-list">
    </ul>
</div>

<script>
$('.clicksy').click(function() {
        $.ajax({
            type: "GET",
            url: "<?php echo $this->url(array(), 'restdepartmentsbycollege', true); ?>/" + $(this).attr('id'),
            success: function(data) {
                $.each(data.data, function(val) {
                    var list_element = $('<li>').addClass('sc-text').text(this.name);
                    var span_element = $('<span>').attr('id', 'sicons');
                    span_element.append($('<a>').attr('href', "mailto:?Subject=" + encodeURIComponent(this.email_subject) + "&Body=" + encodeURIComponent(this.email_body)).addClass('mail-link'));
                    list_element.append(span_element);
                    span_element.append($('<a>').attr('href', this.pdf_link).addClass('pdf-link'));
                    $('#second-list').append(list_element);
                });
            }
        });
    $('#content-first').animate({
        right: '100%'
    }, 500, function() {
        $(this).toggle();
    });
    $('#content-second').toggle().animate({
        left: '0%'
    }, 500, function() {
        
    });
});

$('#header-second-page').click(function() {
    $('#content-first').toggle().animate({
        right: '0%'
    }, 500, function() {
    });
    $('#content-second').animate({
        left: '100%'
    }, 500, function() {
        $(this).toggle();
        $('#second-list').empty();
    });
});


</script>
