<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i>Departments</h2>
		</div>
		<div class="box-content">
			<style type="text/css">
				table.datatable th:first-child,table.datatable th:last-child{
					text-align: center;
				}
				table.datatable th:first-child{
					width: 5%;
				}
				
				table.datatable th:last-child{
					width: 10%;
				}
				table.datatable td:first-child,table.datatable td:last-child{
					text-align: center;
					white-space: nowrap;
				}
			</style>
			
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
				<thead>
					<th>ID</th>
					<th>Name</th>
					<th>Actions</th>
				</thead>
				<tbody>
					<?php foreach($this->departments as $department) :?>
					<tr>
						<td style="text-align:center;white-space:nowrap;width:5%;"><?php echo $department->id; ?></td>
						<td><?php echo $department->name; ?> </td>
						<td style="text-align:center;white-space:nowrap;width:10%;">
							<a href="<?php echo $this->baseUrl('/admin/departments/edit/' . $department->id); ?>" class="btn btn-primary">Edit</a>
						</td>
					</tr>

					<?php endforeach; ?>
				</tbody>
			</table>
			<a href="<?php echo $this->baseUrl('/admin/departments/add'); ?>" class="btn btn-primary">New </a>
		</div>
	</div>
</div>