<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i>Departments</h2>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
				<thead>
					<th>ID</th>
					<th>Name</th>
					<th width="20%">Actions</th>
				</thead>
				<tbody>
					<?php foreach($this->departments as $department) :?>
					<tr>
						<td><?php echo $department->id; ?></td>
						<td><?php echo $department->name; ?> </td>
						<td>
							<a href="<?php echo $this->baseUrl('/admin/departments/edit/' . $department->id); ?>" class="btn btn-primary">Edit</a>
						</td>
					</tr>

					<?php endforeach; ?>
				</tbody>
			</table>
			<a href="<?php echo $this->baseUrl('/admin/departments/add'); ?>" class="btn btn-primary">New </a>
		</div>
	</div>
</div>