<div class="row-fluid">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-user"> </i>Users</h2>
		</div>
		<div class="box-content">
			<table class="table table-striped table-bordered bootstrap-datatable datatable">
				<thead>
					<th>ID</th>
					<th>Username</th>
					<th>First Name</th>
					<th>Last Name</th>
					<th>Role</th>
					<th width="20%">Actions</th>
				</thead>
				<tbody>
					<?php foreach($this->users as $user) :?>
					<tr>
						<td><?php echo $user->id; ?></td>
						<td><?php echo $user->username; ?> </td>
						<td><?php echo $user->first_name; ?> </td>
						<td><?php echo $user->last_name; ?> </td>
						<td><?php echo $user->is_admin; ?></td>
						<td>
							<a href="<?php echo $this->baseUrl('/admin/users/edit/' . $user->id); ?>" class="btn btn-primary">Edit</a>
						</td>
					</tr>

					<?php endforeach; ?>
				</tbody>
			</table>
			<a href="<?php echo $this->baseUrl('/admin/resource/add'); ?>" class="btn btn-primary"> New </a>
		</div>
	</div>
</div>